### ISSUE TITLE
git-lfs pull fail

### ISSUE THREAD

**Issue by j40903272** [fra31/fab-attack#2]
> git-lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/fra31/fab-attack.git/info/lfs'

**Comment by fra31** [comment]
Hi,

I moved datasets and models [here](https://drive.google.com/file/d/1VBYsfON-lo_JQpmaRezSYxmnePmr49FN/view?usp=sharing) and removed the references to Git LFS.

Let me know if it works!

**Comment by j40903272** [comment]
It works great !! Thanks.
